# Generated by Django 5.0.1 on 2024-01-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDjango',
            fields=[
                ('ip_address', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(default='unknown', max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
