# Generated by Django 5.0.1 on 2024-12-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedjango',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devicedjango',
            name='mac_address',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
